### ISSUE TITLE
get_dependency

### ISSUE THREAD

**Issue by sideboltconor** [mattbennett/nameko-sentry#3]
Would it be possible to add a get_dependency method to return the raven client? For times when you want to send a non exception message.

client.captureMessage('Somebody did something sorta strange.')

**Comment by mattbennett** [comment]
I understand the desire here. I wonder if a better way to do it would be to use a [SentryHander](https://docs.getsentry.com/hosted/clients/python/integrations/logging/) and the logging framework.

I've just raised a PR against nameko https://github.com/onefinestay/nameko/pull/313 that loads `LOGGING` config on service startup.

The following `config.yaml` configures `nameko_sentry` and adds a logging `SentryHandler` at the same time.

``` yaml
SENTRY:
    DSN: &sentry_dsn
        https://user:pass@app.getsentry.com/12345
    CLIENT_CONFIG: &sentry_client_config
        site: 'Test Site'

AMQP_URI: amqp://guest:guest@localhost/
LOGGING:
    version: 1
    disable_existing_loggers: false
    formatters:
        simple:
            format: "%(levelname)s:%(name)s - %(message)s"
    handlers:
        console:
            class: logging.StreamHandler
            formatter: simple
        sentry:
            <<: *sentry_client_config
            dsn: *sentry_dsn
            class: raven.handlers.logging.SentryHandler
        sentry_restricted:
            <<: *sentry_client_config
            dsn: *sentry_dsn
            level: WARNING  # restricted to WARNING and above
            class: raven.handlers.logging.SentryHandler
    loggers:
        sentry:
            level: INFO
            handlers: [sentry]
            propagate: False
    root:
        level: INFO
        handlers: [console,sentry_restricted]
```

With this particular config, warnings and above in any logger go to sentry, and there's a specific `sentry` logger will sends info level and above, e.g.

``` python
import logging

logging.getLogger("app").info("logs to console only")
logging.getLogger("sentry").info("logs to sentry only")
logging.getLogger("nameko").warn("logs to console and sentry")
```

The only snag with the above is that the built-in `raven.handlers.logging.SentryHandler` is incompatible with eventlet. It works but you get a traceback on teardown. This can be fixed by subclassing the built-in one to force the handler to use the eventlet http transport:

``` python
from raven.handlers.logging import SentryHandler as RavenSentryHandler
from raven.transport import EventletHTTPTransport

class SentryHandler(RavenSentryHandler):
    def __init__(self, *args, **kwargs):
        kwargs['transport'] = EventletHTTPTransport
        super(SentryHandler, self).__init__(*args, **kwargs)
```

If this is a useful solve for your problem we could add the above subclass into `nameko_sentry`.
